// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OPS.Persistence;

#nullable disable

namespace OPS.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OPS.Domain.Entities.Auth.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<long?>("CloudFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AccountId");

                    b.HasIndex("CloudFileId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts", "Auth");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Auth.AccountRole", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId", "RoleTypeId");

                    b.HasIndex("RoleTypeId");

                    b.ToTable("AccountRoles", "Auth");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Auth.Otp", b =>
                {
                    b.Property<long>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OtpId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(dateadd(minute,(5),getutcdate()))");

                    b.HasKey("OtpId");

                    b.HasIndex("AccountId");

                    b.ToTable("Otps", "Auth");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Core.CloudFile", b =>
                {
                    b.Property<long>("CloudFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CloudFileId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CloudFileId");

                    b.HasIndex("AccountId");

                    b.ToTable("CloudFiles", "Core");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Core.LogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id");

                    b.ToTable("LogEvents", "Core");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.Difficulty", b =>
                {
                    b.Property<long>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DifficultyId"));

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DifficultyId");

                    b.HasIndex("DifficultyName")
                        .IsUnique();

                    b.ToTable("Difficulties", "Enum");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.ProgLanguage", b =>
                {
                    b.Property<long>("ProgLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProgLanguageId"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProgLanguageId");

                    b.HasIndex("Language")
                        .IsUnique();

                    b.ToTable("ProgLanguages", "Enum");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.QuestionType", b =>
                {
                    b.Property<long>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuestionTypeId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("QuestionTypeId");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("QuestionTypes", "Enum");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.RoleType", b =>
                {
                    b.Property<long>("RoleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleTypeId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleTypeId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("RoleTypes", "Enum");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.SocialType", b =>
                {
                    b.Property<long>("SocialTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SocialTypeId"));

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SocialTypeId");

                    b.HasIndex("PlatformName")
                        .IsUnique();

                    b.ToTable("SocialTypes", "Enum");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.ExamCandidate", b =>
                {
                    b.Property<long>("ExamCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExamCandidateId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ExaminationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ExamCandidateId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExaminationId");

                    b.ToTable("ExamCandidates", "Exam");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.Examination", b =>
                {
                    b.Property<long>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExaminationId"));

                    b.Property<DateTime>("ClosesAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OpensAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ExaminationId");

                    b.ToTable("Examinations", "Exam");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.McqAnswer", b =>
                {
                    b.Property<long>("McqAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("McqAnswerId"));

                    b.Property<long>("McqOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("McqAnswerId");

                    b.HasIndex("McqOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("McqAnswers", "Exam");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.McqOption", b =>
                {
                    b.Property<long>("McqOptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("OptionMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("McqOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("McqOptions", "Exam");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.Question", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuestionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<long>("DifficultyId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExaminationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("QuestionTypeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("StatementMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("QuestionId");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("ExaminationId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions", "Exam");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.TestCase", b =>
                {
                    b.Property<long>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestCaseId"));

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("TestCaseId");

                    b.HasIndex("QuestionId");

                    b.ToTable("TestCases", "Exam");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.FlaggedSubmission", b =>
                {
                    b.Property<long>("FlaggedSolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FlaggedSolutionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProblemSubmissionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("FlaggedSolutionId");

                    b.HasIndex("ProblemSubmissionId");

                    b.ToTable("FlaggedSubmissions", "Submit");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.McqSubmission", b =>
                {
                    b.Property<long>("McqSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("McqSubmissionId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<long>("McqOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("McqSubmissionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("McqOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("McqSubmissions", "Submit");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.ProblemSubmission", b =>
                {
                    b.Property<long>("ProblemSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProblemSubmissionId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ProgLanguagesId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProblemSubmissionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProgLanguagesId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ProblemSubmissions", "Submit");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.WrittenSubmission", b =>
                {
                    b.Property<long>("WrittenSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WrittenSubmissionId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("WrittenSubmissionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("QuestionId");

                    b.ToTable("WrittenSubmissions", "Submit");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.AccountSocial", b =>
                {
                    b.Property<long>("SocialLinkId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.HasKey("SocialLinkId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountSocials", "User");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.Profile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProfileId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("BioMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstituteName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProfileId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Profiles", "User");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.SocialLink", b =>
                {
                    b.Property<long>("SocialLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SocialLinkId"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SocialTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("SocialLinkId");

                    b.HasIndex("SocialTypeId");

                    b.ToTable("SocialLinks", "User");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Auth.Account", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Core.CloudFile", "CloudFile")
                        .WithMany("Accounts")
                        .HasForeignKey("CloudFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CloudFile");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Auth.AccountRole", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Enum.RoleType", "RoleType")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RoleType");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Auth.Otp", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", null)
                        .WithMany("Otps")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Core.CloudFile", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("CloudFiles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.ExamCandidate", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("ExamCandidates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OPS.Domain.Entities.Exam.Examination", "Examination")
                        .WithMany("ExamCandidates")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.McqAnswer", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Exam.McqOption", "McqOption")
                        .WithMany("McqAnswers")
                        .HasForeignKey("McqOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Exam.Question", "Question")
                        .WithMany("McqAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("McqOption");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.McqOption", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Exam.Question", "Question")
                        .WithMany("McqQptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.Question", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Enum.Difficulty", "Difficulty")
                        .WithMany("Questions")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Exam.Examination", "Examination")
                        .WithMany("Questions")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Enum.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Examination");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.TestCase", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Exam.Question", "Question")
                        .WithMany("TestCases")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.FlaggedSubmission", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Submit.ProblemSubmission", "ProblemSubmission")
                        .WithMany("FlaggedSubmissions")
                        .HasForeignKey("ProblemSubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProblemSubmission");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.McqSubmission", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("McqSubmissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Exam.McqOption", "McqOption")
                        .WithMany("McqSubmissions")
                        .HasForeignKey("McqOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Exam.Question", "Question")
                        .WithMany("McqSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("McqOption");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.ProblemSubmission", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("ProblemSubmissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Enum.ProgLanguage", "ProgLanguages")
                        .WithMany("ProblemSubmissions")
                        .HasForeignKey("ProgLanguagesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Exam.Question", "Question")
                        .WithMany("ProblemSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ProgLanguages");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.WrittenSubmission", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("WrittenSubmissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.Exam.Question", "Question")
                        .WithMany("WrittenSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.AccountSocial", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithMany("AccountSocials")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OPS.Domain.Entities.User.SocialLink", "SocialLink")
                        .WithMany("AccountSocials")
                        .HasForeignKey("SocialLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SocialLink");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.Profile", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Auth.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("OPS.Domain.Entities.User.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.SocialLink", b =>
                {
                    b.HasOne("OPS.Domain.Entities.Enum.SocialType", "SocialType")
                        .WithMany("SocialLinks")
                        .HasForeignKey("SocialTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SocialType");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Auth.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("AccountSocials");

                    b.Navigation("CloudFiles");

                    b.Navigation("ExamCandidates");

                    b.Navigation("McqSubmissions");

                    b.Navigation("Otps");

                    b.Navigation("ProblemSubmissions");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("WrittenSubmissions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Core.CloudFile", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.Difficulty", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.ProgLanguage", b =>
                {
                    b.Navigation("ProblemSubmissions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.RoleType", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Enum.SocialType", b =>
                {
                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.Examination", b =>
                {
                    b.Navigation("ExamCandidates");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.McqOption", b =>
                {
                    b.Navigation("McqAnswers");

                    b.Navigation("McqSubmissions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Exam.Question", b =>
                {
                    b.Navigation("McqAnswers");

                    b.Navigation("McqQptions");

                    b.Navigation("McqSubmissions");

                    b.Navigation("ProblemSubmissions");

                    b.Navigation("TestCases");

                    b.Navigation("WrittenSubmissions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.Submit.ProblemSubmission", b =>
                {
                    b.Navigation("FlaggedSubmissions");
                });

            modelBuilder.Entity("OPS.Domain.Entities.User.SocialLink", b =>
                {
                    b.Navigation("AccountSocials");
                });
#pragma warning restore 612, 618
        }
    }
}
