export const languages = [
  {
      label: "C++",
      value: "cpp",
      defaultCode:
          "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // Your code here\n    return 0;\n}",
  },
  { label: "Python", value: "python", defaultCode: "# Your code here" },
  {
      label: "Java",
      value: "java",
      defaultCode:
          "public class Main {\n    public static void main(String[] args) {\n        // Your code here\n    }\n}",
  },
  {
      label: "JavaScript",
      value: "javascript",
      defaultCode: "function solve(input) {\n    // Your code here\n}",
  },
  {
      label: "C",
      value: "c",
      defaultCode:
          "#include <stdio.h>\n\nint main() {\n    // Your code here\n    return 0;\n}",
  },
  { label: "Python 2", value: "python2", defaultCode: "# Your code here" },
  { label: "Node.js", value: "nodejs", defaultCode: "function solve(input) {\n    // Your code here\n}" },
  { label: "Groovy", value: "groovy", defaultCode: "println 'Your code here'" },
  { label: "JShell", value: "jshell", defaultCode: "System.out.println('Your code here');" },
  { label: "Haskell", value: "haskell", defaultCode: "main = putStrLn 'Your code here'" },
  { label: "TCL", value: "tcl", defaultCode: "puts 'Your code here'" },
  { label: "Lua", value: "lua", defaultCode: "print('Your code here')" },
  { label: "Ada", value: "ada", defaultCode: "procedure Main is\nbegin\n   -- Your code here\nend Main;" },
  { label: "Common Lisp", value: "commonlisp", defaultCode: "(defun main ()\n  (format t \"Your code here\"))" },
  { label: "D", value: "d", defaultCode: "import std.stdio;\nvoid main() {\n    writeln(\"Your code here\");\n}" },
  { label: "Elixir", value: "elixir", defaultCode: "IO.puts 'Your code here'" },
  { label: "Erlang", value: "erlang", defaultCode: "io:format('Your code here')" },
  { label: "F# (FSharp)", value: "fsharp", defaultCode: "printfn \"Your code here\"" },
  { label: "Fortran", value: "fortran", defaultCode: "program main\n    print *, 'Your code here'\nend program main" },
  { label: "Assembly", value: "assembly", defaultCode: "section .data\n    msg db 'Your code here',0\nsection .text\n    global _start" },
  { label: "Scala", value: "scala", defaultCode: "object Main extends App {\n    println(\"Your code here\")\n}" },
  { label: "PHP", value: "php", defaultCode: "<?php\n// Your code here\n?>" },
  { label: "C#", value: "csharp", defaultCode: "using System;\nclass Program {\n    static void Main() {\n        // Your code here\n    }\n}" },
  { label: "Perl", value: "perl", defaultCode: "print \"Your code here\";" },
  { label: "Ruby", value: "ruby", defaultCode: "puts 'Your code here'" },
  { label: "Go", value: "go", defaultCode: "package main\nimport \"fmt\"\nfunc main() {\n    fmt.Println(\"Your code here\")\n}" },
  { label: "R", value: "r", defaultCode: "print('Your code here')" },
  { label: "Racket", value: "racket", defaultCode: "(define (main) (displayln \"Your code here\"))" },
  { label: "OCaml", value: "ocaml", defaultCode: "print_endline \"Your code here\";" },
  { label: "VB (Visual Basic)", value: "vb", defaultCode: "Module Program\n    Sub Main()\n        ' Your code here\n    End Sub\nEnd Module" },
  { label: "Basic", value: "basic", defaultCode: "PRINT \"Your code here\"" },
  { label: "Bash", value: "bash", defaultCode: "echo 'Your code here'" },
  { label: "Clojure", value: "clojure", defaultCode: "(println \"Your code here\")" },
  { label: "TypeScript", value: "typescript", defaultCode: "function solve(input: string) {\n    // Your code here\n}" },
  { label: "COBOL", value: "cobol", defaultCode: "DISPLAY 'Your code here'" },
  { label: "Kotlin", value: "kotlin", defaultCode: "fun main() {\n    println(\"Your code here\")\n}" },
  { label: "Pascal", value: "pascal", defaultCode: "program Main;\nbegin\n    writeln('Your code here');\nend." },
  { label: "Prolog", value: "prolog", defaultCode: "write('Your code here')." },
  { label: "Rust", value: "rust", defaultCode: "fn main() {\n    println!(\"Your code here\");\n}" },
  { label: "Swift", value: "swift", defaultCode: "print(\"Your code here\")" },
  { label: "Objective-C", value: "objectivec", defaultCode: "#import <Foundation/Foundation.h>\nint main() {\n    @autoreleasepool {\n        NSLog(@\"Your code here\");\n    }\n    return 0;\n}" },
  { label: "Octave", value: "octave", defaultCode: "disp('Your code here')" },
  { label: "Text", value: "text", defaultCode: "Your code here" },
  { label: "Brainfuck", value: "brainfk", defaultCode: ">++++++++[<+++++++++>-]<." },
  { label: "CoffeeScript", value: "coffeescript", defaultCode: "console.log 'Your code here'" },
  { label: "EJS", value: "ejs", defaultCode: "<%= 'Your code here' %>" },
  { label: "Dart", value: "dart", defaultCode: "void main() {\n    print('Your code here');\n}" },
  { label: "Deno", value: "deno", defaultCode: "console.log('Your code here');" },
  { label: "Bun", value: "bun", defaultCode: "console.log('Your code here');" },
];


